INSERT INTO cambio VALUES (1, 'USD', 'BRL', 5.73); 
INSERT INTO cambio VALUES (2, 'USD', 'EUR', 0.84); 
INSERT INTO cambio VALUES (3, 'USD', 'GBP', 0.73); 
INSERT INTO cambio VALUES (4, 'USD', 'ARS', 92.56); 
INSERT INTO cambio VALUES (5, 'USD', 'CLP', 713.30); 
INSERT INTO cambio VALUES (6, 'USD', 'COP', 3665.00);
INSERT INTO cambio VALUES (7, 'USD', 'MXN', 20.15);