server:
  port: 8100
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  bulkhead:
    instances:
      default:
       max-concurrent-calls: 10 
  ratelimiter:
    instances:
      default:
        limit-for-period: 2
        limit-refresh-period: 10s
  retry:
    instances:
      foo-bar:
        max-attempts: 5
        wait-duration: 1s
        enable-exponential-backoff: true
      default:
        max-attempts: 3

spring:
  application:
    name: book-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book_service?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin123
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      fail-on-empty-beans: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  flyway:
    url: jdbc:mysql://localhost:3306/
    schemas: book_service
    user: root
    password: admin123
 
springdoc:
  show-actuator: true
  api-docs:
    path: book-service/v3/api-docs 